version: 0.2

env:
  variables:
    SONAR_PROJECT_KEY: "<project_key>"
    SONAR_HOST_URL: "<your_sonar_url>"
    SONAR_TOKEN: "<your_token>"
    
phases:
  build:
    commands:
      - echo Running SonarQube analysis...
      - sonar-scanner \
        -Dsonar.projectKey=$SONAR_PROJECT_KEY \
        -Dsonar.sources=. \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_TOKEN

artifacts:
  files:
    - '**/*'
